### ISSUE TITLE
Great article about dpi/ppi for articles list

### ISSUE THREAD

**Issue by Arahnoid** [LeaVerou/dpi#79]
Please have a look at article below. I guess it is great to add to articles list.
http://sebastien-gabriel.com/designers-guide-to-dpi/home?utm_content=bufferb152c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by LeaVerou** [comment]
Yes, this is pretty amazing!
Pull request?

**Comment by Arahnoid** [comment]
Sorry but I'm not sure how to do this :( I am pretty new with GIT and Github

**Comment by waldyrious** [comment]
@Arahnoid it's very easy :) you can simply navigate to the file in the github web interface and click the pencil icon to edit the file. After you make the changes, you just click the green "propose file change" button, and then the "send pull request" one (it's a two-step process because you might want to edit several files before sending the pull request of all of them together).

**Comment by waldyrious** [comment]
@Arahnoid you shouldn't close this issue yet, since the pull request (#80) hasn't been merged.

**Comment by Arahnoid** [comment]
@waldyrious sorry i thought what almost a year passed and issue can be closed

**Comment by waldyrious** [comment]
Unfortunately this (long response times) happens sometimes, when the project maintainer is busy with other things. I suggest you to consider reopening the issue until the PR is dealt with.
